services:
  catalogddatabase:
    image: 'mongo'
    container_name: catalog_db
    restart: always
    ports:
      - '27017:27017'
    volumes:
        - mongo_data:/data/db

  catalog.service.api:
    container_name: catalogserviceapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - MongoDbSettings__ConnectionString=mongodb://catalog_db:27017
      - MongoDbSettings__DatabaseName=ProductDb
    depends_on:
      - catalogddatabase
    ports:
      - "5247:8080"
