services:
  catalogddatabase:
    image: 'mongo'
    container_name: catalog_db
    restart: always
    ports:
      - '27017:27017'
    volumes:
        - mongo_data:/data/db

  catalog.service.api:
    container_name: catalogserviceapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=80
      - DatabaseSettings__ConnectionString=mongodb://catalog_db:27017
      - DatabaseSettings__DatabaseName=ProductDb
      - DatabaseSettings__CollectionName=use
    depends_on:
      - catalogddatabase 
    ports:
      - "8000:80"