<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.Types" Version="15.1.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catalog.Service.Domain\Catalog.Service.Domain.csproj" />
  </ItemGroup>

</Project>
